[context.production.environment]
  HUGO_VERSION = "0.83.1"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.83.1"

[build]
  command = "hugo"
  publish = "public"

[[redirects]]
  from = "https://boutiquehearing.net/"
  to = "https://boutiquehearing.com/"
  status = 301
  force = true